import type { Product, User } from "./types"

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Wireless Bluetooth Headphones",
    description: "Premium noise-cancelling headphones with 30-hour battery life and superior sound quality.",
    price: 199.99,
    category: "Electronics",
    image: "/wireless-bluetooth-headphones.jpg",
    stock: 45,
    rating: 4.5,
  },
  {
    id: "2",
    name: "Minimalist Leather Watch",
    description: "Elegant timepiece with genuine leather strap and Swiss movement.",
    price: 149.99,
    category: "Accessories",
    image: "/minimalist-leather-watch.jpg",
    stock: 28,
    rating: 4.8,
  },
  {
    id: "3",
    name: "Organic Cotton T-Shirt",
    description: "Sustainable and comfortable everyday essential in classic fit.",
    price: 34.99,
    category: "Clothing",
    image: "/organic-cotton-tshirt.png",
    stock: 120,
    rating: 4.3,
  },
  {
    id: "4",
    name: "Smart Fitness Tracker",
    description: "Track your health metrics with heart rate monitoring and GPS.",
    price: 89.99,
    category: "Electronics",
    image: "/smart-fitness-tracker.png",
    stock: 67,
    rating: 4.2,
  },
  {
    id: "5",
    name: "Ceramic Coffee Mug Set",
    description: "Handcrafted set of 4 mugs perfect for your morning brew.",
    price: 44.99,
    category: "Home",
    image: "/ceramic-coffee-mug-set.png",
    stock: 89,
    rating: 4.6,
  },
  {
    id: "6",
    name: "Running Sneakers Pro",
    description: "Lightweight running shoes with advanced cushioning technology.",
    price: 129.99,
    category: "Shoes",
    image: "/running-sneakers-pro.jpg",
    stock: 54,
    rating: 4.7,
  },
  {
    id: "7",
    name: "Portable Power Bank",
    description: "20000mAh capacity with fast charging support for all devices.",
    price: 49.99,
    category: "Electronics",
    image: "/portable-power-bank.png",
    stock: 156,
    rating: 4.4,
  },
  {
    id: "8",
    name: "Yoga Mat Premium",
    description: "Non-slip eco-friendly mat for your yoga and fitness routines.",
    price: 59.99,
    category: "Sports",
    image: "/premium-yoga-mat.png",
    stock: 72,
    rating: 4.5,
  },
  {
    id: "9",
    name: "Stainless Steel Water Bottle",
    description: "Insulated bottle keeps drinks cold for 24hrs or hot for 12hrs.",
    price: 29.99,
    category: "Home",
    image: "/stainless-steel-bottle.png",
    stock: 203,
    rating: 4.8,
  },
  {
    id: "10",
    name: "Wireless Charging Pad",
    description: "Fast wireless charging for all Qi-enabled devices.",
    price: 39.99,
    category: "Electronics",
    image: "/wireless-charging-pad.png",
    stock: 88,
    rating: 4.3,
  },
  {
    id: "11",
    name: "Denim Jacket Classic",
    description: "Timeless denim jacket with modern fit and vintage wash.",
    price: 89.99,
    category: "Clothing",
    image: "/denim-jacket-classic.jpg",
    stock: 34,
    rating: 4.6,
  },
  {
    id: "12",
    name: "Sunglasses Polarized",
    description: "UV400 protection with polarized lenses for crystal clear vision.",
    price: 79.99,
    category: "Accessories",
    image: "/sunglasses-polarized.jpg",
    stock: 61,
    rating: 4.4,
  },
]

export const mockUsers: User[] = [
  { id: "1", name: "John Doe", email: "john@example.com", role: "user" },
  { id: "2", name: "Jane Smith", email: "jane@example.com", role: "user" },
  { id: "3", name: "Admin User", email: "admin@example.com", role: "admin" },
  { id: "4", name: "Bob Wilson", email: "bob@example.com", role: "user" },
  { id: "5", name: "Alice Brown", email: "alice@example.com", role: "user" },
]

export const categories = ["All", "Electronics", "Clothing", "Accessories", "Home", "Sports", "Shoes"]
